### ISSUE TITLE
Finalized Search

### ISSUE THREAD

**Issue by RcVincent** [RcVincent/CS-481-Senior-Software#24]
Users can search for:
-Training Docs, their histories, positions and Docs by position

Managers and Admins can search for:
-All positions, all documents, either through the others table as well, position migration requirements and amend these requirements

Mangers can search for the histories of any of their direct employees, with respect to the tiers.

Admins can see any users history and the entire position migration.

**Comment by Tadukoo** [comment]
Covered in many use cases
