### ISSUE TITLE
Manager/Admin creates SOP

### ISSUE THREAD

**Issue by RcVincent** [RcVincent/CS-481-Senior-Software#25]
MSS:
<ol>
<li>Logged-In User navigates to SOP Creation page</li>
<li>Manager/Admin enters title, description, priority, and version</li>
<li>Manager/Admin selects Position(s) for SOP to be under</li>
<li>System creates SOP and notifies Users with the Position(s)</li>
</ol>
 
Extensions:

	1a: User is not Manager or Admin
		.1: Error message is displayed and nothing else, user doesn’t have permission.
		.2: Offer link back to User Home
	3a: Manager/Admin creates Position, return to MSS step 3

Requirements:
* [ ] User accesses System (#8)
* [ ] CreateSOPServlet and create_sop.jsp
* [ ] Messenger System?
* [ ] Find Position queries
* [ ] Insert SOP

**Comment by Tadukoo** [comment]
Was not completed for minimal. Haven't checked yet if done for 50% yet
