### ISSUE TITLE
Manager/Admin creates Position

### ISSUE THREAD

**Issue by RcVincent** [RcVincent/CS-481-Senior-Software#26]
MSS:
<ol>
<li>Logged-In User navigates to Position creation page</li>
<li>Manager/Admin enters title, description, and priority</li>
<li>System creates Position</li>
</ol>
 
Extensions:

	1a: User isn’t Manager or Admin
		.1: Error message is displayed and nothing else, user doesn’t have permission.
		.2: Offer link back to User Home

Requirements:
* [ ] User accesses System (#8)
* [ ] CreatePositionServlet and create_position.jsp
* [ ] Insert Position

**Comment by Tadukoo** [comment]
Not done for minimal. Haven't checked yet if done for 50% yet
