### ISSUE TITLE
Manager/Admin creates Account

### ISSUE THREAD

**Issue by RcVincent** [RcVincent/CS-481-Senior-Software#27]
MSS:
<ol>
<li>Logged-In User navigates to account creation page (link from userhome for manager and admin accounts)</li>
<li>Manager/Admin enters an email and name</li>
<li>Manager/Admin selects Position for new account</li>
<li>System sends a verification email with a link to reset password</li>
<li>User (with created account) resets password</li>
<li>Manager/Admin receives email that account was verified</li>
</ol>
 
Extensions:

	1a: User is not Manager or Admin
		.1: Error message is displayed and nothing else, user doesn’t have permission.
		.2: Offer link back to User Home
	3a: Manager/Admin creates Position, return to MSS step 3

Requirements:
* [ ] User accesses System (#8)
* [ ] CreateAccountServlet and create_account.jsp
* [ ] Messenger system?
* [ ] Find Positions queries
* [ ] Insert User

**Comment by Tadukoo** [comment]
Not actually done - still to this day
