### ISSUE TITLE
Manager overturns Lockout

### ISSUE THREAD

**Issue by RcVincent** [RcVincent/CS-481-Senior-Software#33]
MSS:
<ol>
<li>Manager/Admin views their Users(#35)</li>
<li>Manager/Admin selects the desired User</li>
<li>Manager/Admin changes the User’s lockout flag to false</li>
</ol>

Requirements:
* [ ] Manager/Admin views their Users (#35)
* [x] UserControl overturnLockout
* [ ] User table has locked_out field

**Comment by Tadukoo** [comment]
Assigned to me for 50%
