### ISSUE TITLE
Manager/Admin views their Users

### ISSUE THREAD

**Issue by RcVincent** [RcVincent/CS-481-Senior-Software#35]
MSS:
<ol>
<li>Logged-In User navigates to User Search page</li>
<li>They are shown their subordinates if Manager or all users if Admin</li>
<li>Manager/Admin enters search criteria</li>
<li>Manager/Admin is shown updated users list</li>
</ol>
 
Extensions:

	1a: User is not a Manager or Admin
		.1: Notify user they don’t have permission
		.2: Provide link to return to User Home
	4a: The search criteria doesn’t exist in the database
		.1: Notify the Manager/Admin of no results
		.2: Return to MSS step 3 (or they may return to MSS step 2, by clearing all data)

Requirements:
* [x] User accesses System (#8)
* [ ] UserSearchServlet and user_search.jsp
* [x] Users table in database

**Comment by Tadukoo** [comment]
Not finished in minimal, working on for 50%
