### ISSUE TITLE
Manager/Admin archives User

### ISSUE THREAD

**Issue by RcVincent** [RcVincent/CS-481-Senior-Software#42]
MSS:
<ol>
<li>Manager/Admin views their Users (#35)</li>
<li>Manager/Admin selects a user (or multiple?)</li>
<li>Manager/Admin clicks to archive them</li>
<li>Manager/Admin must confirm archiving</li>
<li>System marks users as archived</li>
</ol>

Requirements:
* [ ] Manager/Admin views their Users (#35)
* [ ] UserControl archive function
* [ ] User table (archive flag)

**Comment by Tadukoo** [comment]
Not finished in minimal, possibly can for 50%?
