### ISSUE TITLE
Manager archives SOP

### ISSUE THREAD

**Issue by RcVincent** [RcVincent/CS-481-Senior-Software#43]
MSS:
<ol>
<li>Manager/Admin views their SOPs(#76)</li>
<li>Manager/Admin selects an SOP</li>
<li>Manager/Admin clicks to archive them</li>
<li>Manager/Admin must confirm archiving</li>
<li>System marks SOPs as archived</li>
</ol>

Requirements:
* [ ] Manager/Admin views their SOPs(#76)
* [ ] SOPControl archive function
* [ ] SOP table (archive flag)

**Comment by Tadukoo** [comment]
Not finished in minimal, probably can for 50%?
