### ISSUE TITLE
Manager/Admin deletes Position

### ISSUE THREAD

**Issue by RcVincent** [RcVincent/CS-481-Senior-Software#44]
MSS:
<ol>
<li>Manager/Admin views their Positions (#82)</li>
<li>Manager/Admin selects a Position</li>
<li>Manager/Admin clicks to delete them</li>
<li>Manager/Admin must confirm before deletion occurs</li>
<li>System removes the Position from the database</li>
</ol>

Requirements:
* [ ] Manager/Admin views their Positions(#82)
* [ ] PositionControl delete function
* [ ] Position table

**Comment by Tadukoo** [comment]
Not done for minimal, likely won't be for 50%, put in final
