### ISSUE TITLE
Manager/Admin views their Positions

### ISSUE THREAD

**Issue by Zackeree** [RcVincent/CS-481-Senior-Software#82]
MSS:
<ol>
<li>Logged-In User navigates to Position Search page</li>
<li>They are shown their created Positions if Manager or all Positions if Admin</li>
<li>Manager/Admin enters search criteria</li>
<li>Manager/Admin is shown updated Position list</li>
<li>Manager/Admin may delete Position (#44)</li>
</ol>
 
Extensions:

    1a: User is not a Manager or Admin
        .1: Notify user they don’t have permission
        .2: Provide link to return to User Home
    4a: The search criteria doesn’t exist in the database
        .1: Notify the Manager/Admin of no results
        .2: Return to MSS step 3 (or they may return to MSS step 2, by clearing all data)

Requirements:
* [ ] User accesses System (#8)
* [ ] PositionSearchServlet and position_search.jsp
* [ ] Position table in database

**Comment by Tadukoo** [comment]
Not done for minimal, will be for 50%
