### ISSUE TITLE
Manager/Admin edits Position

### ISSUE THREAD

**Issue by Zackeree** [RcVincent/CS-481-Senior-Software#83]
MSS:
<ol>
<li>Manager/Admin views their Positions (#82)</li>
<li>Manager/Admin selects a Position</li>
<li>Manager/Admin clicks to edit</li>
<li>Manager/Admin changes respective fields</li>
<li>Manager/Admin must confirm before edits occur</li>
<li>System updates the Position in the database</li>
</ol>

Requirements:
* [ ] Manager/Admin views their Positions(#82)
* [ ] PositionControl edit/modify function

**Comment by Tadukoo** [comment]
Not done for minimal, should be for 50%
